version: "3.8"
services:
  volume-data-transformer:
    build:
      context: ../../../VolumeDataTransformer
      dockerfile: ../../../../docker/aggTrades/live/transformation/Dockerfile
    volumes:
      - ./src/:/app
      - ./logs/:/app/logs
    environment:
      AWS_ACCESS_KEY_ID: AKIAS625BHFC5UUKQVYE
      AWS_SECRET_ACCESS_KEY: 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
      AWS_BUCKET_NAME: xtrus31
      AWS_REGION_NAME: eu-north-1
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      PYSPARK_SUBMIT_ARGS: "--master local[2] pyspark-shell"
      BEARER_TOKEN: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5MDIxMjgwNywianRpIjoiZGUyNzcyNjgtZGI4ZS00MTgyLTllODItZTkxYzgwM2I3YTE0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImJvdF9jaW5kZXgiLCJuYmYiOjE2OTAyMTI4MDd9.cmddgaA1uAGESp03yur_Ix9JsZIegdUWiSlIpsyK7YCWWZZp4e7H-6haLKoXXvMRUW8FGlNLf5GvX9H4Coh5Y_KfUulBqiYkhGKcBpH7CMv8jf3Z8Sjlpk0VXs_0NGQiagEq7i7eI9BN4IDmGPmOYtYrBmAMlWiCW91XpBokqjoHqQZ-00WEP_RYIeWem-831pEBGR_IPCVygGtwv9D75_PKqllYzyZz4J1Aidtyfosa1ICtjncda6PZoUcjXaJ_3SioFX7imWab31paMHnNOhzC7urgBc184PGuZgzjAps-mk92IBRxYT7LPjhMuS-WaBASAsVuarpGiJnQ3XJ-vpuMn3zc1YsTB3nNGjgy7ogkxBPRNeLCqomkqzGpc-KzvSIH9TWTS2g7boiQbwwlIlGkaQReYI2TjgdQEv9ox3HAHWr6X2RGy4oD66GtyeYym2lQEGMuxGDWgV-jcUFaUE5mQU_bq8byzq15BOaU3FoVOhHzXLw1eqjHPFMlGvzAU9vzF92uZ17zPCLketD2KMYDNlDdKyFGh-wWIoPkHxGXIpVniJVI5iJ1i5lPochMXzWLI4fVVnpbH64PgFgXrmAL516v8mZN4C1EPc_WSj-lk2vIjmYsod9RDgyEO7yl4JsEZU1Q2kY6wgXFSQEiICCKgg37d9yleRKRf_Onmlk
