Binance-data-vision:
  symbols:
    - APTUSDT
  stream: aggTrades
  timeframes:
    - 1h
  bucket: production-trustia-raw-data
  start_date: 2024-09-20
  base_url: https://data.binance.vision/data/

logging:
  level: INFO
  rotation_when: midnight
  interval: 1
  backup_count: 7

Ta-lib:
  symbol: BTCUSDT
  stream: klines
  timeframe: 1h
  bucket: production-trustia-raw-data
  bars: time_bars
  start_date: 2024-01-01
  end_date: 2024-09-20
  custom_indicators:  [
          {'name': 'ema', 'params': {'length': 20}},  # Exponential Moving Average
          {'name': 'macd', 'params': {}},  # MACD
          {'name':'rsi', 'params': {'length': 14}} # RSI
          ]
  market: 'futures'
