Binance-data-vision:
  symbols:
    - APTUSDT
  stream: aggTrades
  timeframes:
    - 1h
  bucket: production-trustia-raw-data
  start_date: 2024-09-20
  base_url: https://data.binance.vision/data/

logging:
  level: INFO
  rotation_when: midnight
  interval: 1
  backup_count: 7
