app:
  name: MyApp Development
  version: 1.0
  debug: true

api:
  base_url: https://dev-api.myapp.com
  timeout: 30

symbols:
  - btcusdt

streams :
  - aggTrades

timeframes:
  - 1h

buckets:
  binance_data_vision: production_trustia_raw_data