app:
  name: MyApp Development
  version: 1.0
  debug: true

api:
  base_url: https://dev-api.myapp.com
  timeout: 30

symbols:
  - btcusdt
  - ethusdt
  - ltcusdt

timeframes:
  - 1h
  - 4h

DBV_bucket_name:
 - production_trustia_raw_data