services:
  transformation-binance-klines:
    build:
      context: ..
      dockerfile: ./docker/dsol.Dockerfile
    volumes:
      - ../src/cores/cicada-transformation/indicators/ta-lib/main.py:/app/main.py
      - ../src/cores/cicada-transformation/indicators/ta-lib/talib_processing_controller.py:/app/talib_processing_controller.py
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    command: [ "python", "main.py" ]
