services:
  transformation-binance-klines:
    build:
      context: ..
      dockerfile: ./docker/dsol.Dockerfile
    volumes:
      - ../src/cores/cicada-transformation/indicators/ta-lib/main.py:/app/main.py
      - ../src/cores/cicada-transformation/indicators/ta-lib/talib_processing_controller.py:/app/talib_processing_controller.py
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    command: [ "python", "main.py" ]

#  ingestion-binance-stream-klines:
#    build:
#      context: ..
#      dockerfile: ./docker/dsol.Dockerfile
#    volumes:
#      - ../src/cores/cicada-ingestion/data-providers/Binance/sources/ingestion-data-vision-binance/main.py:/app/main.py
#      - ../src/cores/cicada-ingestion/data-providers/Binance/sources/ingestion-data-vision-binance/controller_binance_data_vision.py:/app/controller_binance_data_vision.py
#    environment:
#      - PYTHONUNBUFFERED=1
#      - ENV=development
#      - STREAM=klines
#    command: [ "python3", "main.py" ]
