tasks = [
    (
        "post",
        "/bapi/futures/v1/public/future/data/global-long-short-account-ratio",
        {"name": "BTCUSDT", "periodMinutes": 60},
        "global_long_short_account_ratio",
    ),
    (
        "post",
        "/bapi/futures/v1/public/future/data/open-interest-stats",
        {"name": "BTCUSDT", "periodMinutes": 60},
        "open_interest_stats",
    ),
    (
        "get",
        "/bapi/futures/v1/public/future/trading/statistic/getAltcoinWeekIndicator?beginDate=2024-03-18&endDate=2024-03-25&limit=1",
        None,
        "altcoin_week_indicator",
    ),
    (
        "post",
        "/bapi/composite/v1/friendly/pgc/news/list",
        {"name": "BTCUSDT", "periodMinutes": 60},
        "news_list",
    ),
    (
        "post",
        "/bapi/futures/v1/public/future/data/open-interest-stats",
        {"name": "BTCUSDT", "periodMinutes": 5},
        "open_interest_stats_5m",
    ),
    (
        "post",
        "/bapi/futures/v1/public/future/data/long-short-account-ratio",
        {"name": "BTCUSDT", "periodMinutes": 5},
        "long_short_account_ratio",
    ),
    (
        "post",
        "/bapi/futures/v1/public/future/data/long-short-position-ratio",
        {"name": "BTCUSDT", "periodMinutes": 5},
        "long_short_position_ratio",
    ),
    (
        "post",
        "/bapi/futures/v1/public/future/data/global-long-short-account-ratio",
        {"name": "BTCUSDT", "periodMinutes": 5},
        "global_long_short_account_ratio_5m",
    ),
    (
        "post",
        "/bapi/futures/v1/public/future/data/taker-long-short-ratio",
        {"name": "BTCUSDT", "periodMinutes": 5},
        "taker_long_short_ratio",
    ),
    (
        "get",
        "/bapi/futures/v1/public/future/data/basis?period=5m&limit=30&pair=BTCUSDT&contractType=PERPETUAL",
        None,
        "basis",
    ),
    (
        "get",
        "/bapi/futures/v1/public/future/cores/get-funding-info",
        None,
        "funding_info",
    ),
    (
        "post",
        "/bapi/futures/v1/public/future/cores/get-funding-rate-history",
        {"symbol": "BTCUSDT", "page": 1, "rows": 42},
        "funding_rate_history",
    ),
    ("get", "/fapi/v1/premiumIndex", None, "premium_index"),
    (
        "get",
        "/bapi/composite/v1/public/bigdata/option/trendingTop5?underlying=ETHUSDT",
        None,
        "trending_top5_eth",
    ),
    (
        "get",
        "/bapi/composite/v1/public/bigdata/option/trendingTop5?underlying=BTCUSDT",
        None,
        "trending_top5_btc",
    ),
    (
        "get",
        "/bapi/composite/v1/public/bigdata/option/openInterestByStrike?underlying=BTCUSDT",
        None,
        "open_interest_by_strike",
    ),
    (
        "get",
        "/bapi/composite/v1/public/bigdata/option/openInterestByExpiry?underlying=BTCUSDT",
        None,
        "open_interest_by_expiry",
    ),
    (
        "get",
        "/bapi/composite/v1/public/bigdata/option/takerFlow?underlying=BTCUSDT",
        None,
        "taker_flow",
    ),
    (
        "get",
        "/bapi/eoptions/v1/public/eoptions/exchange/tGroup?contract=BTCUSDT",
        None,
        "exchange_tgroup",
    ),
    (
        "get",
        "/bapi/composite/v1/public/bigdata/option/marketHist?underlying=BTCUSDT&period=1d&limit=60",
        None,
        "market_hist",
    ),
]
