version: "3.8"

networks:
  spark-network:
    external: true

services:
  spark-master:
    build:
      context: ../../..
      dockerfile: ../../../docker/base/spark-master/Dockerfile
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-network
    environment:
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    command:
      [
        "/entrypoint.sh",
        "spark-class",
        "org.apache.spark.deploy.master.Master",
        "--host",
        "spark-master",
      ]
